### ISSUE TITLE
README: More descriptive alt text or caption for architecture diagram

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/cloud-tasks-pizza-map#5]
The current alt text on the architectural diagram is "Architecture Diagram". However, this kind of alt text does not help the visually impaired understand the architecture.

Two options:
* Make the alt text more detailed so screen readers describe the architecture
* Add a caption to the image (preferably using &lt;figure> HTML5 attribute to group the image and caption if GFM supports) which succinctly explains the architecture.

https://www.phase2technology.com/blog/no-more-excuses
https://www.w3.org/WAI/tutorials/images/complex/

**Comment by grant** [comment]
Added a more detailed `alt` text that describes the architecture.
See #6.
